---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeuler-pkgship-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: "csi-disk"
